name: Deploy Frontend

on:
  push:
    branches: 
      -  main 
      - develop 
      - 'feature/*'
  workflow_dispatch:

env:
  PROJECT_ID: training-batch-05
  REGION: us-east1
  PROD_BUCKET: gs://campers-front

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el código
        uses: actions/checkout@v3

      - name: 🛠️ Instalar dependencias
        run: npm install

      - name: 🏗️ Construir el sitio (React)
        run: npm run build

      - name: 🔐 Autenticarse con GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY_FR }}

      - name: 🪣 Subir archivos al bucket
        run: |
          BUCKET=${{ env.PROD_BUCKET }}
          gsutil -m rsync -r build gs://$BUCKET
          gsutil -m setmeta -h "Cache-Control:no-cache" gs://$BUCKET/**

      - name: 🌍 Configurar sitio como página web (opcional, solo la primera vez)
        run: |
          BUCKET=${{ env.PROD_BUCKET }}
          gsutil web set -m index.html -e index.html gs://$BUCKET
